/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeSubscriptionRouteImport } from './routes/welcome-subscription'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as StudentWalletRouteImport } from './routes/_student.wallet'
import { Route as StudentSupportCenterRouteImport } from './routes/_student.support-center'
import { Route as StudentSubscriptionsRouteImport } from './routes/_student.subscriptions'
import { Route as StudentRankingsRouteImport } from './routes/_student.rankings'
import { Route as StudentPurchasedRouteImport } from './routes/_student.purchased'
import { Route as StudentProfileRouteImport } from './routes/_student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/_student.notifications'
import { Route as StudentHistoryRouteImport } from './routes/_student.history'
import { Route as StudentDashboardRouteImport } from './routes/_student.dashboard'
import { Route as StudentTestsIndexRouteImport } from './routes/_student.tests.index'
import { Route as StudentCoursesIndexRouteImport } from './routes/_student.courses.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as StudentCoursesCourseIdRouteImport } from './routes/_student.courses.$courseId'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTokensRouteImport } from './routes/_admin.admin.tokens'
import { Route as AdminAdminTestsRouteImport } from './routes/_admin.admin.tests'
import { Route as AdminAdminSupportRouteImport } from './routes/_admin.admin.support'
import { Route as AdminAdminSubscriptionsRouteImport } from './routes/_admin.admin.subscriptions'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminReviewsRouteImport } from './routes/_admin.admin.reviews'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin.admin.notifications'
import { Route as AdminAdminMonitoringRouteImport } from './routes/_admin.admin.monitoring'
import { Route as AdminAdminMarketingRouteImport } from './routes/_admin.admin.marketing'
import { Route as AdminAdminCoursesRouteImport } from './routes/_admin.admin.courses'
import { Route as AdminAdminCourseReviewsRouteImport } from './routes/_admin.admin.course-reviews'
import { Route as AdminAdminBugsRouteImport } from './routes/_admin.admin.bugs'
import { Route as StudentTestsTestIdIndexRouteImport } from './routes/_student.tests.$testId.index'
import { Route as StudentPortalCourseIdIndexRouteImport } from './routes/_student.portal.$courseId.index'
import { Route as StudentTestsTestIdAttemptRouteImport } from './routes/_student.tests.$testId.attempt'
import { Route as StudentPortalCourseIdCompleteRouteImport } from './routes/_student.portal.$courseId.complete'
import { Route as StudentPortalCourseIdAssessmentRouteImport } from './routes/_student.portal.$courseId.assessment'
import { Route as AdminAdminVideosCourseIdRouteImport } from './routes/_admin.admin.videos.$courseId'
import { Route as AdminAdminQuestionsTestIdRouteImport } from './routes/_admin.admin.questions.$testId'
import { Route as StudentTestsTestIdReviewAttemptIdRouteImport } from './routes/_student.tests.$testId.review.$attemptId'

const WelcomeSubscriptionRoute = WelcomeSubscriptionRouteImport.update({
  id: '/welcome-subscription',
  path: '/welcome-subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWalletRoute = StudentWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSupportCenterRoute = StudentSupportCenterRouteImport.update({
  id: '/support-center',
  path: '/support-center',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubscriptionsRoute = StudentSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRankingsRoute = StudentRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPurchasedRoute = StudentPurchasedRouteImport.update({
  id: '/purchased',
  path: '/purchased',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTestsIndexRoute = StudentTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIndexRoute = StudentCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentCoursesCourseIdRoute = StudentCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTokensRoute = AdminAdminTokensRouteImport.update({
  id: '/admin/tokens',
  path: '/admin/tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTestsRoute = AdminAdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSupportRoute = AdminAdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSubscriptionsRoute = AdminAdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReviewsRoute = AdminAdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMonitoringRoute = AdminAdminMonitoringRouteImport.update({
  id: '/admin/monitoring',
  path: '/admin/monitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMarketingRoute = AdminAdminMarketingRouteImport.update({
  id: '/admin/marketing',
  path: '/admin/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCoursesRoute = AdminAdminCoursesRouteImport.update({
  id: '/admin/courses',
  path: '/admin/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCourseReviewsRoute = AdminAdminCourseReviewsRouteImport.update({
  id: '/admin/course-reviews',
  path: '/admin/course-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBugsRoute = AdminAdminBugsRouteImport.update({
  id: '/admin/bugs',
  path: '/admin/bugs',
  getParentRoute: () => AdminRoute,
} as any)
const StudentTestsTestIdIndexRoute = StudentTestsTestIdIndexRouteImport.update({
  id: '/tests/$testId/',
  path: '/tests/$testId/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPortalCourseIdIndexRoute =
  StudentPortalCourseIdIndexRouteImport.update({
    id: '/portal/$courseId/',
    path: '/portal/$courseId/',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentTestsTestIdAttemptRoute =
  StudentTestsTestIdAttemptRouteImport.update({
    id: '/tests/$testId/attempt',
    path: '/tests/$testId/attempt',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentPortalCourseIdCompleteRoute =
  StudentPortalCourseIdCompleteRouteImport.update({
    id: '/portal/$courseId/complete',
    path: '/portal/$courseId/complete',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentPortalCourseIdAssessmentRoute =
  StudentPortalCourseIdAssessmentRouteImport.update({
    id: '/portal/$courseId/assessment',
    path: '/portal/$courseId/assessment',
    getParentRoute: () => StudentRoute,
  } as any)
const AdminAdminVideosCourseIdRoute =
  AdminAdminVideosCourseIdRouteImport.update({
    id: '/admin/videos/$courseId',
    path: '/admin/videos/$courseId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminQuestionsTestIdRoute =
  AdminAdminQuestionsTestIdRouteImport.update({
    id: '/admin/questions/$testId',
    path: '/admin/questions/$testId',
    getParentRoute: () => AdminRoute,
  } as any)
const StudentTestsTestIdReviewAttemptIdRoute =
  StudentTestsTestIdReviewAttemptIdRouteImport.update({
    id: '/tests/$testId/review/$attemptId',
    path: '/tests/$testId/review/$attemptId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome-subscription': typeof WelcomeSubscriptionRoute
  '/dashboard': typeof StudentDashboardRoute
  '/history': typeof StudentHistoryRoute
  '/notifications': typeof StudentNotificationsRoute
  '/profile': typeof StudentProfileRoute
  '/purchased': typeof StudentPurchasedRoute
  '/rankings': typeof StudentRankingsRoute
  '/subscriptions': typeof StudentSubscriptionsRoute
  '/support-center': typeof StudentSupportCenterRoute
  '/wallet': typeof StudentWalletRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/bugs': typeof AdminAdminBugsRoute
  '/admin/course-reviews': typeof AdminAdminCourseReviewsRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/tests': typeof AdminAdminTestsRoute
  '/admin/tokens': typeof AdminAdminTokensRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/courses/': typeof StudentCoursesIndexRoute
  '/tests/': typeof StudentTestsIndexRoute
  '/admin/questions/$testId': typeof AdminAdminQuestionsTestIdRoute
  '/admin/videos/$courseId': typeof AdminAdminVideosCourseIdRoute
  '/portal/$courseId/assessment': typeof StudentPortalCourseIdAssessmentRoute
  '/portal/$courseId/complete': typeof StudentPortalCourseIdCompleteRoute
  '/tests/$testId/attempt': typeof StudentTestsTestIdAttemptRoute
  '/portal/$courseId/': typeof StudentPortalCourseIdIndexRoute
  '/tests/$testId/': typeof StudentTestsTestIdIndexRoute
  '/tests/$testId/review/$attemptId': typeof StudentTestsTestIdReviewAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome-subscription': typeof WelcomeSubscriptionRoute
  '/dashboard': typeof StudentDashboardRoute
  '/history': typeof StudentHistoryRoute
  '/notifications': typeof StudentNotificationsRoute
  '/profile': typeof StudentProfileRoute
  '/purchased': typeof StudentPurchasedRoute
  '/rankings': typeof StudentRankingsRoute
  '/subscriptions': typeof StudentSubscriptionsRoute
  '/support-center': typeof StudentSupportCenterRoute
  '/wallet': typeof StudentWalletRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/bugs': typeof AdminAdminBugsRoute
  '/admin/course-reviews': typeof AdminAdminCourseReviewsRoute
  '/admin/courses': typeof AdminAdminCoursesRoute
  '/admin/marketing': typeof AdminAdminMarketingRoute
  '/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/reviews': typeof AdminAdminReviewsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/tests': typeof AdminAdminTestsRoute
  '/admin/tokens': typeof AdminAdminTokensRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/courses': typeof StudentCoursesIndexRoute
  '/tests': typeof StudentTestsIndexRoute
  '/admin/questions/$testId': typeof AdminAdminQuestionsTestIdRoute
  '/admin/videos/$courseId': typeof AdminAdminVideosCourseIdRoute
  '/portal/$courseId/assessment': typeof StudentPortalCourseIdAssessmentRoute
  '/portal/$courseId/complete': typeof StudentPortalCourseIdCompleteRoute
  '/tests/$testId/attempt': typeof StudentTestsTestIdAttemptRoute
  '/portal/$courseId': typeof StudentPortalCourseIdIndexRoute
  '/tests/$testId': typeof StudentTestsTestIdIndexRoute
  '/tests/$testId/review/$attemptId': typeof StudentTestsTestIdReviewAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome-subscription': typeof WelcomeSubscriptionRoute
  '/_student/dashboard': typeof StudentDashboardRoute
  '/_student/history': typeof StudentHistoryRoute
  '/_student/notifications': typeof StudentNotificationsRoute
  '/_student/profile': typeof StudentProfileRoute
  '/_student/purchased': typeof StudentPurchasedRoute
  '/_student/rankings': typeof StudentRankingsRoute
  '/_student/subscriptions': typeof StudentSubscriptionsRoute
  '/_student/support-center': typeof StudentSupportCenterRoute
  '/_student/wallet': typeof StudentWalletRoute
  '/admin/login': typeof AdminLoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_admin/admin/bugs': typeof AdminAdminBugsRoute
  '/_admin/admin/course-reviews': typeof AdminAdminCourseReviewsRoute
  '/_admin/admin/courses': typeof AdminAdminCoursesRoute
  '/_admin/admin/marketing': typeof AdminAdminMarketingRoute
  '/_admin/admin/monitoring': typeof AdminAdminMonitoringRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_admin/admin/reviews': typeof AdminAdminReviewsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/subscriptions': typeof AdminAdminSubscriptionsRoute
  '/_admin/admin/support': typeof AdminAdminSupportRoute
  '/_admin/admin/tests': typeof AdminAdminTestsRoute
  '/_admin/admin/tokens': typeof AdminAdminTokensRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_student/courses/$courseId': typeof StudentCoursesCourseIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_student/courses/': typeof StudentCoursesIndexRoute
  '/_student/tests/': typeof StudentTestsIndexRoute
  '/_admin/admin/questions/$testId': typeof AdminAdminQuestionsTestIdRoute
  '/_admin/admin/videos/$courseId': typeof AdminAdminVideosCourseIdRoute
  '/_student/portal/$courseId/assessment': typeof StudentPortalCourseIdAssessmentRoute
  '/_student/portal/$courseId/complete': typeof StudentPortalCourseIdCompleteRoute
  '/_student/tests/$testId/attempt': typeof StudentTestsTestIdAttemptRoute
  '/_student/portal/$courseId/': typeof StudentPortalCourseIdIndexRoute
  '/_student/tests/$testId/': typeof StudentTestsTestIdIndexRoute
  '/_student/tests/$testId/review/$attemptId': typeof StudentTestsTestIdReviewAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/welcome-subscription'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/purchased'
    | '/rankings'
    | '/subscriptions'
    | '/support-center'
    | '/wallet'
    | '/admin/login'
    | '/auth/callback'
    | '/admin/bugs'
    | '/admin/course-reviews'
    | '/admin/courses'
    | '/admin/marketing'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/tests'
    | '/admin/tokens'
    | '/admin/users'
    | '/courses/$courseId'
    | '/admin/'
    | '/courses/'
    | '/tests/'
    | '/admin/questions/$testId'
    | '/admin/videos/$courseId'
    | '/portal/$courseId/assessment'
    | '/portal/$courseId/complete'
    | '/tests/$testId/attempt'
    | '/portal/$courseId/'
    | '/tests/$testId/'
    | '/tests/$testId/review/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/welcome-subscription'
    | '/dashboard'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/purchased'
    | '/rankings'
    | '/subscriptions'
    | '/support-center'
    | '/wallet'
    | '/admin/login'
    | '/auth/callback'
    | '/admin/bugs'
    | '/admin/course-reviews'
    | '/admin/courses'
    | '/admin/marketing'
    | '/admin/monitoring'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/admin/tests'
    | '/admin/tokens'
    | '/admin/users'
    | '/courses/$courseId'
    | '/admin'
    | '/courses'
    | '/tests'
    | '/admin/questions/$testId'
    | '/admin/videos/$courseId'
    | '/portal/$courseId/assessment'
    | '/portal/$courseId/complete'
    | '/tests/$testId/attempt'
    | '/portal/$courseId'
    | '/tests/$testId'
    | '/tests/$testId/review/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/welcome-subscription'
    | '/_student/dashboard'
    | '/_student/history'
    | '/_student/notifications'
    | '/_student/profile'
    | '/_student/purchased'
    | '/_student/rankings'
    | '/_student/subscriptions'
    | '/_student/support-center'
    | '/_student/wallet'
    | '/admin/login'
    | '/auth/callback'
    | '/_admin/admin/bugs'
    | '/_admin/admin/course-reviews'
    | '/_admin/admin/courses'
    | '/_admin/admin/marketing'
    | '/_admin/admin/monitoring'
    | '/_admin/admin/notifications'
    | '/_admin/admin/reviews'
    | '/_admin/admin/settings'
    | '/_admin/admin/subscriptions'
    | '/_admin/admin/support'
    | '/_admin/admin/tests'
    | '/_admin/admin/tokens'
    | '/_admin/admin/users'
    | '/_student/courses/$courseId'
    | '/_admin/admin/'
    | '/_student/courses/'
    | '/_student/tests/'
    | '/_admin/admin/questions/$testId'
    | '/_admin/admin/videos/$courseId'
    | '/_student/portal/$courseId/assessment'
    | '/_student/portal/$courseId/complete'
    | '/_student/tests/$testId/attempt'
    | '/_student/portal/$courseId/'
    | '/_student/tests/$testId/'
    | '/_student/tests/$testId/review/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WelcomeSubscriptionRoute: typeof WelcomeSubscriptionRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-subscription': {
      id: '/welcome-subscription'
      path: '/welcome-subscription'
      fullPath: '/welcome-subscription'
      preLoaderRoute: typeof WelcomeSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/wallet': {
      id: '/_student/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof StudentWalletRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/support-center': {
      id: '/_student/support-center'
      path: '/support-center'
      fullPath: '/support-center'
      preLoaderRoute: typeof StudentSupportCenterRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/subscriptions': {
      id: '/_student/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof StudentSubscriptionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/rankings': {
      id: '/_student/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof StudentRankingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/purchased': {
      id: '/_student/purchased'
      path: '/purchased'
      fullPath: '/purchased'
      preLoaderRoute: typeof StudentPurchasedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile': {
      id: '/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/notifications': {
      id: '/_student/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/history': {
      id: '/_student/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/dashboard': {
      id: '/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/tests/': {
      id: '/_student/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof StudentTestsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/courses/': {
      id: '/_student/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof StudentCoursesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/courses/$courseId': {
      id: '/_student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof StudentCoursesCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tokens': {
      id: '/_admin/admin/tokens'
      path: '/admin/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminAdminTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tests': {
      id: '/_admin/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminAdminTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/support': {
      id: '/_admin/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/subscriptions': {
      id: '/_admin/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminAdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reviews': {
      id: '/_admin/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/monitoring': {
      id: '/_admin/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminAdminMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/marketing': {
      id: '/_admin/admin/marketing'
      path: '/admin/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminAdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/courses': {
      id: '/_admin/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminAdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/course-reviews': {
      id: '/_admin/admin/course-reviews'
      path: '/admin/course-reviews'
      fullPath: '/admin/course-reviews'
      preLoaderRoute: typeof AdminAdminCourseReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bugs': {
      id: '/_admin/admin/bugs'
      path: '/admin/bugs'
      fullPath: '/admin/bugs'
      preLoaderRoute: typeof AdminAdminBugsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/tests/$testId/': {
      id: '/_student/tests/$testId/'
      path: '/tests/$testId'
      fullPath: '/tests/$testId/'
      preLoaderRoute: typeof StudentTestsTestIdIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/portal/$courseId/': {
      id: '/_student/portal/$courseId/'
      path: '/portal/$courseId'
      fullPath: '/portal/$courseId/'
      preLoaderRoute: typeof StudentPortalCourseIdIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/tests/$testId/attempt': {
      id: '/_student/tests/$testId/attempt'
      path: '/tests/$testId/attempt'
      fullPath: '/tests/$testId/attempt'
      preLoaderRoute: typeof StudentTestsTestIdAttemptRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/portal/$courseId/complete': {
      id: '/_student/portal/$courseId/complete'
      path: '/portal/$courseId/complete'
      fullPath: '/portal/$courseId/complete'
      preLoaderRoute: typeof StudentPortalCourseIdCompleteRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/portal/$courseId/assessment': {
      id: '/_student/portal/$courseId/assessment'
      path: '/portal/$courseId/assessment'
      fullPath: '/portal/$courseId/assessment'
      preLoaderRoute: typeof StudentPortalCourseIdAssessmentRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/videos/$courseId': {
      id: '/_admin/admin/videos/$courseId'
      path: '/admin/videos/$courseId'
      fullPath: '/admin/videos/$courseId'
      preLoaderRoute: typeof AdminAdminVideosCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/questions/$testId': {
      id: '/_admin/admin/questions/$testId'
      path: '/admin/questions/$testId'
      fullPath: '/admin/questions/$testId'
      preLoaderRoute: typeof AdminAdminQuestionsTestIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_student/tests/$testId/review/$attemptId': {
      id: '/_student/tests/$testId/review/$attemptId'
      path: '/tests/$testId/review/$attemptId'
      fullPath: '/tests/$testId/review/$attemptId'
      preLoaderRoute: typeof StudentTestsTestIdReviewAttemptIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminBugsRoute: typeof AdminAdminBugsRoute
  AdminAdminCourseReviewsRoute: typeof AdminAdminCourseReviewsRoute
  AdminAdminCoursesRoute: typeof AdminAdminCoursesRoute
  AdminAdminMarketingRoute: typeof AdminAdminMarketingRoute
  AdminAdminMonitoringRoute: typeof AdminAdminMonitoringRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminReviewsRoute: typeof AdminAdminReviewsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSubscriptionsRoute: typeof AdminAdminSubscriptionsRoute
  AdminAdminSupportRoute: typeof AdminAdminSupportRoute
  AdminAdminTestsRoute: typeof AdminAdminTestsRoute
  AdminAdminTokensRoute: typeof AdminAdminTokensRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminQuestionsTestIdRoute: typeof AdminAdminQuestionsTestIdRoute
  AdminAdminVideosCourseIdRoute: typeof AdminAdminVideosCourseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBugsRoute: AdminAdminBugsRoute,
  AdminAdminCourseReviewsRoute: AdminAdminCourseReviewsRoute,
  AdminAdminCoursesRoute: AdminAdminCoursesRoute,
  AdminAdminMarketingRoute: AdminAdminMarketingRoute,
  AdminAdminMonitoringRoute: AdminAdminMonitoringRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminReviewsRoute: AdminAdminReviewsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSubscriptionsRoute: AdminAdminSubscriptionsRoute,
  AdminAdminSupportRoute: AdminAdminSupportRoute,
  AdminAdminTestsRoute: AdminAdminTestsRoute,
  AdminAdminTokensRoute: AdminAdminTokensRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminQuestionsTestIdRoute: AdminAdminQuestionsTestIdRoute,
  AdminAdminVideosCourseIdRoute: AdminAdminVideosCourseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentPurchasedRoute: typeof StudentPurchasedRoute
  StudentRankingsRoute: typeof StudentRankingsRoute
  StudentSubscriptionsRoute: typeof StudentSubscriptionsRoute
  StudentSupportCenterRoute: typeof StudentSupportCenterRoute
  StudentWalletRoute: typeof StudentWalletRoute
  StudentCoursesCourseIdRoute: typeof StudentCoursesCourseIdRoute
  StudentCoursesIndexRoute: typeof StudentCoursesIndexRoute
  StudentTestsIndexRoute: typeof StudentTestsIndexRoute
  StudentPortalCourseIdAssessmentRoute: typeof StudentPortalCourseIdAssessmentRoute
  StudentPortalCourseIdCompleteRoute: typeof StudentPortalCourseIdCompleteRoute
  StudentTestsTestIdAttemptRoute: typeof StudentTestsTestIdAttemptRoute
  StudentPortalCourseIdIndexRoute: typeof StudentPortalCourseIdIndexRoute
  StudentTestsTestIdIndexRoute: typeof StudentTestsTestIdIndexRoute
  StudentTestsTestIdReviewAttemptIdRoute: typeof StudentTestsTestIdReviewAttemptIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDashboardRoute: StudentDashboardRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentPurchasedRoute: StudentPurchasedRoute,
  StudentRankingsRoute: StudentRankingsRoute,
  StudentSubscriptionsRoute: StudentSubscriptionsRoute,
  StudentSupportCenterRoute: StudentSupportCenterRoute,
  StudentWalletRoute: StudentWalletRoute,
  StudentCoursesCourseIdRoute: StudentCoursesCourseIdRoute,
  StudentCoursesIndexRoute: StudentCoursesIndexRoute,
  StudentTestsIndexRoute: StudentTestsIndexRoute,
  StudentPortalCourseIdAssessmentRoute: StudentPortalCourseIdAssessmentRoute,
  StudentPortalCourseIdCompleteRoute: StudentPortalCourseIdCompleteRoute,
  StudentTestsTestIdAttemptRoute: StudentTestsTestIdAttemptRoute,
  StudentPortalCourseIdIndexRoute: StudentPortalCourseIdIndexRoute,
  StudentTestsTestIdIndexRoute: StudentTestsTestIdIndexRoute,
  StudentTestsTestIdReviewAttemptIdRoute:
    StudentTestsTestIdReviewAttemptIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WelcomeSubscriptionRoute: WelcomeSubscriptionRoute,
  AdminLoginRoute: AdminLoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
